// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoP-yPAI3JA0xYIryUg9i-drpsnPpZbc8',
    appId: '1:1061671691247:web:dc5242e0c040e29272cc1a',
    messagingSenderId: '1061671691247',
    projectId: 'alphasignage-48b92',
    authDomain: 'alphasignage-48b92.firebaseapp.com',
    databaseURL: 'https://alphasignage-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'alphasignage-48b92.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3iqi5JWfsIWNn6--OULpXgOhKT46zz8w',
    appId: '1:1061671691247:android:687c844bc40469d272cc1a',
    messagingSenderId: '1061671691247',
    projectId: 'alphasignage-48b92',
    databaseURL: 'https://alphasignage-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'alphasignage-48b92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCGGvi_DScIcgtYWuIeAvVGEd0javVFuw',
    appId: '1:1061671691247:ios:6d8f33566f93828d72cc1a',
    messagingSenderId: '1061671691247',
    projectId: 'alphasignage-48b92',
    databaseURL: 'https://alphasignage-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'alphasignage-48b92.appspot.com',
    iosClientId: '1061671691247-p6s11u9nca1jlh1o8hjuuenahapf7hfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitScreenApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCGGvi_DScIcgtYWuIeAvVGEd0javVFuw',
    appId: '1:1061671691247:ios:6d8f33566f93828d72cc1a',
    messagingSenderId: '1061671691247',
    projectId: 'alphasignage-48b92',
    databaseURL: 'https://alphasignage-48b92-default-rtdb.firebaseio.com',
    storageBucket: 'alphasignage-48b92.appspot.com',
    iosClientId: '1061671691247-p6s11u9nca1jlh1o8hjuuenahapf7hfe.apps.googleusercontent.com',
    iosBundleId: 'com.example.splitScreenApp',
  );
}
